### ISSUE TITLE
Bolton - What to do?

### ISSUE THREAD

**Issue by kulaszewicz** [PJMPR/Westeros#2]
**RECIPES**
1 Ustalenie jednostek i typów miar dla poszczególnych encji
2. Zaprojektowanie bazy danych z podziałem na tabele, kolumny, relacje
3. Napisanie klas z geterami, seterami
4. Kalkulator kalorii, białka etc...

**Comment by Ventrae** [comment]
3 - **_DONE_**

**Comment by kulaszewicz** [comment]
2 - **_DONE_**
4 - **_DONE_**
