### ISSUE TITLE
[STARK] lista rzeczy do zrobienia

### ISSUE THREAD

**Issue by Pawel095** [PJMPR/Westeros#4]
Listy najpopularniejszych (ilość odwiedzin)
   Przepisy
   Diety
Ranking Cen (od najmniejszych)
System Ocen do:
   Przepisów
   Diet
Komentarze do ocen
Kalkulatory do wszystkiego wyżej

**Comment by robertmielewczyk** [comment]
wow, ale super nie mogę się doczekać, aż wszyscy zabierzemy się do roboty!
